apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ereg-cache
  namespace: team-dialog
  labels:
    team: team-dialog
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: team-dialog
      application: ereg-splitter-change
      access: readwrite
    - team: team-dialog
      application: ereg-sf
      access: read