apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ereg-splitter-change
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 8192Mi
    requests:
      cpu: 100m
      memory: 4096Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/sbs/ereg-splitter-change/default
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srveregsplchg
  env:
    - name: KAFKA_BROKERS
      value: SASL_SSL://b27apvl00045.preprod.local:8443,SASL_SSL://b27apvl00046.preprod.local:8443,SASL_SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_CLIENTID
      value: ereg-splitter-change
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: privat-whatever
    - name: EREG_UEURL
      value: 'https://data.brreg.no/enhetsregisteret/api/underenheter/lastned'
    - name: EREG_UEACCEPT
      value: 'application/vnd.brreg.enhetsregisteret.underenhet.v2+gzip;charset=UTF-8'
    - name: EREG_OEURL
      value: 'https://data.brreg.no/enhetsregisteret/api/enheter/lastned'
    - name: EREG_OEACCEPT
      value: 'application/vnd.brreg.enhetsregisteret.enhet.v2+gzip;charset=UTF-8'
    - name: RUN_EACH_MORNING
      value: 'TRUE'
    - name: MAX_ATTEMPTS
      value: '24'
    - name: MS_BETWEEN_RETRIES
      value: '1800000'
    - name: VAULT_INSTANCE
      value: PREPROD