apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ereg-splitter-change
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 9Gi
    requests:
      cpu: 100m
      memory: 3Gi
  accessPolicy:
    outbound:
      external:
        - host: data.brreg.no
  envFrom:
    - secret: ereg-splitter-change
  filesFrom:
    - secret: ereg-splitter-change
  kafka:
    pool: nav-prod # enum of nav-dev, nav-prod
  env:
    - name: KAFKA_BROKERS_ON_PREM
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00148.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443,SASL_SSL://a01apvl00150.adeo.no:8443
    - name: KAFKA_CLIENTID
      value: ereg-splitter-change
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC #onprem: public-ereg-cache-org-json
      value: team-dialog.ereg-cache
    - name: EREG_UEURL
      value: 'https://data.brreg.no/enhetsregisteret/api/underenheter/lastned'
    - name: EREG_UEACCEPT
      value: 'application/vnd.brreg.enhetsregisteret.underenhet.v1+gzip;charset=UTF-8'
    - name: EREG_OEURL
      value: 'https://data.brreg.no/enhetsregisteret/api/enheter/lastned'
    - name: EREG_OEACCEPT
      value: 'application/vnd.brreg.enhetsregisteret.enhet.v1+gzip;charset=UTF-8'
    - name: RUN_EACH_MORNING
      value: 'TRUE'
    - name: MAX_ATTEMPTS
      value: '24'
    - name: MS_BETWEEN_RETRIES
      value: '1800000'
    - name: VAULT_INSTANCE
      value: GCP
    - name: KAFKA_USER # When fetching on-prem srv password from gcp secret
      value: srveregsplchg
    - name: KAFKA_POLL_DURATION
      value: '10000'