apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: argus-sykmeldinger
  namespace: default
  labels:
    team: dsopkontroll
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 768Mi
  webproxy: true
  ingresses: ["https://argus-sykmeldinger.nais.adeo.no"]
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/argus-sykmeldinger/default
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvargussm
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: DATABASE_HOST
      value: A01DBVL011.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: argus-sykmeldinger
    - name: DATABASE_VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: JWT_ISSUER
      value: https://sts.windows.net/62366534-1ec3-4962-8869-9b5535279d0b/
    - name: JWT_JWKS_URI
      value: https://login.windows.net/common/discovery/keys